service: node-in-aws-backend-sheva

provider:
  name: aws
  runtime: nodejs16.x
  apiGateway: 
      shouldStartNameWithService: true
  profile: sheva_admin
  region: 'eu-central-1'
  environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
      PG_HOST: ${env:PG_HOST}
      PG_PORT: ${env:PG_PORT}
      PG_DATABASE: ${env:PG_DATABASE}
      PG_USERNAME: ${env:PG_USERNAME}
      PG_PASSWORD: ${env:PG_PASSWORD}

plugins:
  - serverless-plugin-typescript

functions:
  getProductsList:
    handler: ./functions/products/getProductsList/getProductsList.handler
    events:
      - http: 
          path: /products
          method: get
  getProductById:
    handler: ./functions/products/getProductById/getProductById.handler
    events:
      - http: 
          path: /products/{productId}
          method: get
  createProduct:
    handler: ./functions/products/createProduct/createProduct.handler
    events:
      - http: 
          path: /products
          method: post