service: authorization-service
   
provider:
  name: aws
  runtime: nodejs16.x
  apiGateway: 
      shouldStartNameWithService: true
  profile: dm-admin
  region: 'eu-central-1'
  environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
      BUCKET_NAME: ${self:custom.client.bucketName}
      # ARN: FUNCTION_ARN: "arn:aws:lambda:${self:provider.region}:function:${self:service}-${self:provider.stage}-basicAuthorizer"



custom:
  client:
    bucketName: product-aws-bucket-v2
  s3BucketName: ${self:custom.client.bucketName}
  

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-stack-output

functions:
  basicAuthorizer:
    handler: ./functions/basicAuthorizer.handler
    description: 'Authorizer'
  getToken:
    handler: ./functions/getToken.handler
    events:
      - http:
          path: /token
          method: post
	
resources:
  Outputs:
    StackAuth:
      Value: !GetAtt BasicAuthorizerLambdaFunction.Arn
      Export:
        Name: 'authorization-service-dev-Arn'
       