service: import-service
   
provider:
  name: aws
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 
            - s3:ListBucket
          Resource: 
            - 'arn:aws:s3:::sheva-aws-bucket-v2'
        - Effect: Allow
          Action: 
            - s3:*
          Resource: 
            - 'arn:aws:s3:::sheva-aws-bucket-v2/*'
  runtime: nodejs16.x
  apiGateway: 
      shouldStartNameWithService: true
  profile: sheva_admin
  region: 'eu-central-1'
  environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
      NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
      BUCKET_NAME: ${self:custom.client.bucketName}


custom:
  client:
    bucketName: sheva-aws-bucket-v2
  s3BucketName: ${self:custom.client.bucketName}


plugins:
  - serverless-plugin-typescript

functions:
  importProductsFile:
    handler: ./functions/importProductsFile/importProductsFile.handler
    events:
      - http: 
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: ./functions/importFileParser/importFileParser.handler
    events: 
      - s3: 
         bucket: ${self:custom.client.bucketName}
         event: s3:ObjectCreated:*
         existing: true
         rules:
            - prefix: uploaded/
            - suffix: .csv